Feature/write content
mash-up-kr/groby-iOS pull request #10
Opened 2018-08-18 12:30 UTC by tak8997

내용 작성 페이지 뼈대 작업.

2018-08-22 14:17 UTC, JeaSungLEE requested changes
엄청 빨리 해줬넹 .. 갓 병탁 쩌러

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +    private var imageUrls: [NSURL] = []
왜 NSURL일까여??
밑에서 사용할때 URL이던데 URL로 저장하면 as? URL을 안해도 될거 같은데.. 아닌가요? 다른곳에서 가져올때 NSURL로 가져오나요??

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +        print(itemHeight)
print는 지워주셔도 될거 같습니당

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +            guard let imageData: Data = try! Data.init(contentsOf: imageUrl as URL), let image: UIImage = UIImage(data: imageData) else {
try! 를 ?로 바꾸면 좋을거 같아영!

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +            OperationQueue.main.addOperation {
operationQueue가 복잡하니 dispatchqueue로 바꿔주시면 더 좋을것 같습니다.
부스트코스에서는 학습용으로 오퍼레이션큐였는데 여긴 dispatchqueue 로 합시당!

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +        dismiss(animated: false, completion: nil)
여기랑 위에는 에니메이션이 왜 없을까요?? 에니메이션 있는게 더 좋지 않을까요?

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +    private lazy var imagePicker: UIImagePickerController = {
private Good Good  👏
아래 함수들도 private할수있는걸 할수이쓰면 좋을거 가타영

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +            print("camera")
카메라 부분이 구현이 안된것 같습니당.

2018-08-22 14:17 UTC, JeaSungLEE commented on groby/MakeTab1SecondViewController.swift
> +            self.present(self.imagePicker, animated: true, completion: nil)
클로저안에서 self 사용할땐  [weak self]로 하고
`(action: UIAlertAction)`이부분은 사용하지 않는거 같은데 _로 바꾸면 좋아요

2018-08-22 14:19 UTC, JeaSungLEE commented
<img width="339" alt="image" src="https://user-images.githubusercontent.com/13097922/44469139-c7dd2e80-a661-11e8-833e-0bbbb30aaae7.png">
아 그리고 스크롤이 세로로 됩니당

2018-08-26 10:07 UTC, tak8997 commented on groby/MakeTab1SecondViewController.swift
> +            print("camera")
나중에 하게ㅋㅋ

2018-09-02 08:40 UTC, merged